PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZBC_MAP CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZBC_MAP-BAPINAME .
    FIELD ZBC_MAP-BAPI_TAB .
    FIELD ZBC_MAP-BAPI_FLD .
    FIELD ZBC_MAP-FIELDNAME .
    FIELD ZBC_MAP-ODATA_FLD .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZBC_MAP-BAPINAME .
    FIELD ZBC_MAP-BAPI_TAB .
    FIELD ZBC_MAP-BAPI_FLD .
    FIELD ZBC_MAP-FIELDNAME .
    FIELD ZBC_MAP-ODATA_FLD .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
