"Name: \PR:SAPLMRM_BAPI\EX:BAPI_INCOMINGINVOICE_CREAT1_G8\EI
ENHANCEMENT 0 ZMRM_INCOMING_INVOICE.
CALL METHOD ZCL_COS_DATA_BUILD=>cos_proccessor
  EXPORTING
    is_bapi_doc_header = HEADERDATA
  CHANGING
    ct_bapi_glaccount  = GLACCOUNTDATA[]
    ct_bapi_extension2 = EXTENSIONIN[]
    .
ENDENHANCEMENT.
