@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_2915B2697B2A'

extend view C_PROFITCENTERQ2701 with ZZ1_QG2PZSSI4VW65FPXGPH4KT63KQ
  
{ 
  ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
