@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_E343869BDD7D'

extend view C_GLLINEITEMSQ0001 with ZZ1_2DPGXM3G4PTXFHVWXOPNJ33TTY
  
{ 
  ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
