@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_421281CF6D6F'

extend view I_GLACCOUNTLINEITEMSEMTAG with ZZ1_6UQZYXQHC4QFE7RHNJ4JOYLDWY
  
{ 
  _Extension.ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
