@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_CC0A0BBA18B6'

extend view C_PROFITABILITY_Q0002 with ZZ1_XLWDDEZSRDM2QIOKFI7K6TQ34M
  
{ 
  ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
