@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_DBFFAD33ED2D'

extend view E_FINANCIALPLANNINGENTRYITEM with ZZ1_BVLEE7ZZHUAPXLGF2QINMUSDRE
  
{ 
  Persistence.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
