@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_241ED505418F'

extend view A_FINPLANNINGENTRYITEMTP with ZZ1_GDZNTQOPCVEKRKSTR2NFYRFGS4
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
