@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_9A72FCBAF12B'

extend view FAC_DART_Z3_GL_LEDGER_ITEM with ZZ1_2GGLAGLTAQWAYI54QIXWP4TPD4
  
{ 
  ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
