@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_15F889E327AA'

extend view C_PROFITANDLOSSQ2901 with ZZ1_URLOOU2X54B7TMZBOBC3EV65SE
  
{ 
  ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
