@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_72F6B3CAEC62'

extend view C_PROJECTPLANACTQ2201 with ZZ1_VAJ46RQMMYLVIQC34ACM3MJ424
  
{ 
  ZZ1_TRANSACTIONKEY_APC as ZZ1_TRANSACTIONKEY_APC
}
