@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_CA9C0537F0BB'

extend view A_JOURNALENTRYITEMBASIC with ZZ1_4TNGVVHI75SKNVDTDBCEVYF3SA
  
{ 
  ZZ1_PRODUCTCODE_COB as ZZ1_PRODUCTCODE_COB
}
