@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_D412FDA5C298'

extend view I_GLACCOUNTLINEITEMCUBE with ZZ1_ENDBAHAXZZCY2XSW2VLLFWNT54
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
