@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_A24F59B57915'

extend view I_REALTIMERPTDFINDATAENHCD with ZZ1_RW5BURKYQFKFSG6JEGKHXLCYHE
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
