@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_BD15B7459951'

extend view C_GOODSMOVEMENTQUERY with ZZ1_VGQY6627ANEHDCS5YZJFZRNSMM
  
{ 
  ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
