@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_02911D36519D'

extend view C_SERVICEORDERQRY2401 with ZZ1_RUQVLEZCAFGGCWTXOOOMHUIS2I
  
{ 
  ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
