@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_249A37F06666'

extend view FAC_GLACCOUNTLINEITEM with ZZ1_NSB3KAV6XMHME5TM3DOUNW7UTY
  
{ 
  I_GLACCOUNTLINEITEM.ZZ1_ICNNO_COB as ZZ1_ICNNO_COB
}
