@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_C46ADE437850'

extend view FAC_DART_Z3_AR_OPENITEM with ZZ1_GEEDVXJFDUETNNBGLVG7YVCQXA
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
