@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_BD664C00DE3F'

extend view FINAC_SELECTION with ZZ1_CDOSI43NBNSUWBGXWM2MR4DMUQ
  
{ 
  I_GLACCOUNTLINEITEM.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
