@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_86A63064BF99'

extend view E_SUPPLIERINVOICEITEMGLACCT with ZZ1_RF5ZXMCZGK4Q7V5642V3NUT4NI
  
{ 
  Persistence.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
