@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_14258C3F6395'

extend view C_PROFITCENTERQ2701 with ZZ1_S7W3ZDXSUC5FMW2KSE2TTHTL7M
  
{ 
  ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
