@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_D1EBF7D3DDFC'

extend view A_FINPLANENTRYITEMVARIABLEFIX with ZZ1_2JJ4V6DMBBZ2UADBWH2HAER5JI
  
{ 
  _Extension.ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
