@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_91C0D3D94F2F'

extend view C_PROJECTQ2201 with ZZ1_KJOI3GGUTG2DTQK4TO3HPJM7DU
  
{ 
  ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
