@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_1902F6A6D432'

extend view A_OPENINGBALANCE with ZZ1_AOHPOS3ULV37RIFGUBXW25FBJM
  
{ 
  ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
