@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_F95C70D46944'

extend view E_PURREQNACCTASSGMT with ZZ1_YKB7VMJPLTXWZW2GIYMNJM2REM
  
{ 
  Persistence.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
