@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_7584264A2EB0'

extend view I_GLACCOUNTLINEITEM with ZZ1_PV6HGOS54XYZROHLONK7SYHNTM
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
