@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_82E57FBB791B'

extend view C_SALESORDERQ2301 with ZZ1_MYYRDP7M5LIJAXHHSXYTIRBS4M
  
{ 
  ZZ1_VEHICLENO_COB as ZZ1_VEHICLENO_COB
}
