@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_22FD7F81E3BE'

extend view C_OPLACCTGDOCITEMCORRESPNC with ZZ1_MKH6PNHO5NHUOJR5BVKQ6NN6BA
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
