@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_3D308486FFB2'

extend view C_JOURNALENTRYITEMBROWSER with ZZ1_ZTE2W4US2IX6GCKJNVQN4GRGXU
  
{ 
  _Extension.ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
