@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_C4AFB9E8E01B'

extend view C_PROFITABILITY_Q0001 with ZZ1_P27254DG3OLBP5SAQ3ACYB7BLA
  
{ 
  ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
