@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_56318802AE82'

extend view C_PROFITANDLOSSPLANACTQ2903 with ZZ1_3ME3PSALP47XVVHRUX63EQXLHM
  
{ 
  ZZ1_THIRDPARTYREF_APC as ZZ1_THIRDPARTYREF_APC
}
