@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_8E7E8F9CA037'

extend view C_GENERICPLANQ3001 with ZZ1_LEWJZ6AWH6E63IGSWYEF5P5TWY
  
{ 
  ZZ1_HOLMANPO_APC as ZZ1_HOLMANPO_APC
}
