@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_9B5221F35399'

extend view C_FINANCIALSTATEMENTKPI with ZZ1_5TN4ZFM2FBYV4FJYZGYQNV7YLY
  
{ 
  ZZ1_TRANSACTIONKEY_ASC as ZZ1_TRANSACTIONKEY_ASC
}
