@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_4B545FE62C4F'

extend view C_COSTREVNREASSGMTACTIVEITEM with ZZ1_6XLSQQIHJA7TKBPWFMDYDNTSKE
  
{ 
  _Extension.ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
