@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_8A1759B36D5A'

extend view C_SALESORDERQ2301 with ZZ1_OYLT56ZIVTDZGNW3IX3DXE2RSM
  
{ 
  ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
