@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_5D7259B1B846'

extend view C_FUNCTIONALAREASQ2801 with ZZ1_5R34GHAKWC5FTZDPWL3AWXD6YI
  
{ 
  ZZ1_CLIENTCODE_COB as ZZ1_CLIENTCODE_COB
}
