@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_B6E68F2F31BB'

extend view C_PROJECTPLANACTQ2201 with ZZ1_VBKLXPF4KH6IJ7VLRXVOENWKHA
  
{ 
  ZZ1_PRODUCTCODE_APC as ZZ1_PRODUCTCODE_APC
}
