@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_234B4303FA8B'

extend view I_GLACCTBALANCECOMPRNCUBE with ZZ1_LK6ELFGFN6ZG5DPQH7SMXGMLM4
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
