@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_908762D9FE90'

extend view C_FINPLANNINGUPLOADITEM with ZZ1_PQDVQSAJWCH2TY6T64QGGKOZII
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
