@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_872C05132C87'

extend view FINAC_SELECTION with ZZ1_HBAUOLU6GLFCVJCSWK2XKR7GN4
  
{ 
  I_GLACCOUNTLINEITEM.ZZ1_PRODUCTCODE_COB as ZZ1_PRODUCTCODE_COB
}
