@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_5C72BC65F74F'

extend view C_COSTCENTERQ2001 with ZZ1_A72S5PJQMZEELHVMY4URHQQMOQ
  
{ 
  ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
