@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_CA45A44F24C2'

extend view C_MARKETSEGMENTPLANACTQ2501 with ZZ1_DA7ORC3ARV6X2QZ6IRH26BQP7I
  
{ 
  ZZ1_PRICINGELEMENT_APC as ZZ1_PRICINGELEMENT_APC
}
