@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_56384D4E8988'

extend view C_AVGDAILYTRIALBALANCE with ZZ1_KGB4UGKLQH6SMQELYIE7VHOH3Q
  
{ 
  I_AvgDailyBalKeyFig.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
