@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_555D474923D5'

extend view I_JOURNALENTRYITEMCUBE with ZZ1_CHKLI3XXS7DIXCLQ2RBIEAT2K4
  
{ 
  _Extension.ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
