@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_CCC5FB799B42'

extend view I_MATRIXCNSLDTNFNDNPERIODIC with ZZ1_BGAULN2LABP4MIJU2BBJVAU77I
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_CJE as ZZ1_TRANSACTIONKEY_CJE
}
