@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_3FF63B9EE906'

extend view C_PROFITANDLOSSPLANACTQ2903 with ZZ1_GRCIFUGXVAEYAPJWH2XAEMUEPA
  
{ 
  ZZ1_VEHICLENO_APC as ZZ1_VEHICLENO_APC
}
