@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_6C6F83CD44C0'

extend view C_DRCTACTYALLOCATIONACTIVEITEM with ZZ1_SMQTSUWZPHZXPK5CTW4QYOIRHU
  
{ 
  _Extension.ZZ1_HOLMANPO_COB as ZZ1_HOLMANPO_COB
}
