@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_AA67C0D84C73'

extend view C_MARKETSEGMENTQ2501 with ZZ1_KUXGABSTGQ7P53WND5D4DN2OCM
  
{ 
  ZZ1_PRODUCTCODE_COB as ZZ1_PRODUCTCODE_COB
}
