@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_C5734310693D'

extend view I_ACCOUNTINGDOCUMENTJOURNAL with ZZ1_C337KAW32AQXNKGDWLW7F4Q62E
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
