@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_4BA69EB51A86'

extend view C_PROFITANDLOSSQ2901 with ZZ1_W6DVK5WNOZDD7E5F27YLUHSYMY
  
{ 
  ZZ1_PRODUCTCODE_COB as ZZ1_PRODUCTCODE_COB
}
