@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_B1A1664BF755'

extend view C_GLLINEITEMSQ0001 with ZZ1_PRPBO3MJNWO2KVZWPY4FAWRGCA
  
{ 
  ZZ1_VEHICLENO_COB as ZZ1_VEHICLENO_COB
}
