@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_069ECDA1F873'

extend view A_SUPPLIERINVOICEITEMGLACCT with ZZ1_YUCY4PWFMLTW4YO5HUISJ5JCII
  
{ 
  _ItemGLAcctExtension.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
