@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_C11D7C6DADC8'

extend view I_CNSLDTNINTEGRPTDFINDATA with ZZ1_T2QDAK7YN4AHNSK2KWTV7S4FDQ
  
{ 
  _Extension.ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
