@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_A55EACE6F42A'

extend view I_GLACCTBALANCECOMPRNCUBE with ZZ1_S22VVGCQLGPSFBH6URZ2ZSLSQA
  
{ 
  _Extension.ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
