@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_1D31400F48F3'

extend view FAC_GLACCOUNTLINEITEM with ZZ1_XCFVN364MZ263W5ZSSK5AV6NLE
  
{ 
  I_GLACCOUNTLINEITEM.ZZ1_SOURCE_COB as ZZ1_SOURCE_COB
}
