@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_802341FD0159'

extend view C_PROJECTPLANACTQ2203 with ZZ1_MZYHV6MP45CMSZAWR27KFGS7CI
  
{ 
  ZZ1_TRANSACTIONKEY_APC as ZZ1_TRANSACTIONKEY_APC
}
