@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_6E694AFDC7CF'

extend view C_PROJECTPLANACTQ2201 with ZZ1_35EWUY3NRFV2WSXGVJDNVC3KPA
  
{ 
  ZZ1_PRICINGELEMENT_APC as ZZ1_PRICINGELEMENT_APC
}
