@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_D8A472C808E3'

extend view C_FUNCTIONALAREASQ2801 with ZZ1_P7PKCYCJJPVSICZFIGUEYXWYRU
  
{ 
  ZZ1_SOURCE_COB as ZZ1_SOURCE_COB
}
