@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_77D3251032FE'

extend view I_MATRIXCNSLDTNFOUNDATION with ZZ1_MB62ZFFHZ64PSZAPSUY26V7NRM
  
{ 
  _Extension.ZZ1_THIRDPARTYREF_CJE as ZZ1_THIRDPARTYREF_CJE
}
