@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_4C0CC5DE3229'

extend view C_PROFITCENTERQ2701 with ZZ1_JSTK3VRF24UDZCQDC77CRFXCBM
  
{ 
  ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
