@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_A082B66B8326'

extend view C_INTERNALORDERPLANACTQ2101 with ZZ1_EXIGVJ2SBPYJOPZQ2EWXLRPD7Q
  
{ 
  ZZ1_HOLMANPO_APC as ZZ1_HOLMANPO_APC
}
