@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_F7E24E42D9F7'

extend view A_SUPPLIERINVOICEITEMGLACCT with ZZ1_2RWHRDPB2NXAOURXHASE3CLE7A
  
{ 
  _ItemGLAcctExtension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
