@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_BCDA51B0F400'

extend view I_MATRIXCNSLDTNFNDNFORYTDMODE with ZZ1_2FSGMK4YJUDBY3L3NRGWXIS24A
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_CJE as ZZ1_TRANSACTIONKEY_CJE
}
