@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_DAAE6E38349B'

extend view I_DRCTACTIVITYALLOCATIONITEMTP with ZZ1_ITMOT2QPEFRMF5U4HO5PZNDRJY
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
