@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_841523D63273'

extend view I_GLACCOUNTLINEITEM with ZZ1_KI5W5EGJ5YNVWK327OO425LGHQ
  
{ 
  _Extension.ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
