@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_463F23EFC4D2'

extend view C_REALTIMERPTDFINDATAENHCD with ZZ1_KITPLRIY2G5IIHNN3QB25HOLQ4
  
{ 
  RealTimeRptdFinData.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
