@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_910DCA718D9B'

extend view A_FINPLANNINGENTRYITEM with ZZ1_LOVYZTFJNGC5Q77UETZE67RZJE
  
{ 
  ZZ1_PRODUCTCODE_COB as ZZ1_PRODUCTCODE_COB
}
