@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_66014A91B952'

extend view C_INTERNALORDERPLANACTQ2101 with ZZ1_EAXQM2MZ4PGGMXHRECYYUSAQBE
  
{ 
  ZZ1_TRANSACTIONKEY_APC as ZZ1_TRANSACTIONKEY_APC
}
