@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_4120BCD36C5C'

extend view I_MATRIXCNSLDTNFNDNFORYTDMODE with ZZ1_POI3TVHVDDR5U262TFCNS23O3U
  
{ 
  _Extension.ZZ1_THIRDPARTYREF_CJE as ZZ1_THIRDPARTYREF_CJE
}
