@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_71B0D7E777B9'

extend view C_PROFITABILITY_Q0001 with ZZ1_ZAO47Y5X4EMZZHBFYBMKAMMEEE
  
{ 
  ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
