@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_0485EA07802E'

extend view C_PROFITABILITY_Q0002 with ZZ1_SWX6SICA6XUO5UBBYDNXTRGTAY
  
{ 
  ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
