@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_8ACA373A0154'

extend view C_FUNCTIONALAREAPLANACTQ2801 with ZZ1_UQ7IWNGHICITMMGIYYKL7QUMYY
  
{ 
  ZZ1_SERIALNO_APC as ZZ1_SERIALNO_APC
}
