@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_05E7450ED02D'

extend view C_ALLOCRUNJOURNALENTRYITEM with ZZ1_KHXWZXYXEMRFR6T7Y4HHMUGTVY
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
