@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_D2CA91C23212'

extend view C_FINPLANNINGUPLOADITEM with ZZ1_BN34AGUHGXP5V4QGWUTQMZ5D3Y
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
