@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_1212ED721F8D'

extend view E_CNSLDTNGROUPJRNLENTRYITEM with ZZ1_VS2MS7BCBKSSR3FOHWDRXDWIUA
  
{ 
  Persistence.ZZ1_TRANSACTIONKEY_CJE as ZZ1_TRANSACTIONKEY_CJE
}
