@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_F51607B9B4D3'

extend view I_COSTREVNREASSIGNMENTITEMTP with ZZ1_XJB7CCMBR6XNVTTCGVOODDZY2I
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
