@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_701C6F3770B9'

extend view C_DRCTACTYALLOCATIONACTIVEITEM with ZZ1_NWQCPGEV74ISQ5V44VDAZFB6CM
  
{ 
  _Extension.ZZ1_PRODUCTCODE_COB as ZZ1_PRODUCTCODE_COB
}
