@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_1AC1B2C10446'

extend view C_PROFITANDLOSSPLANACTQ2903 with ZZ1_SWQVU7YW6L2TJLGZCK2HUVCEM4
  
{ 
  ZZ1_PRODUCTCODE_APC as ZZ1_PRODUCTCODE_APC
}
