@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_E72DF28D2C01'

extend view C_COSTREVNREASSGMTACTIVEITEM with ZZ1_JXETXN354EZBON53KHQJR476QE
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
