@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_B1A12205C13D'

extend view C_GENERICPLANQ3001 with ZZ1_K7NKNYZ5PDDVUCOZ7RCSCIMNH4
  
{ 
  ZZ1_THIRDPARTYREF_APC as ZZ1_THIRDPARTYREF_APC
}
