@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_6CE01C1367B7'

extend view C_PROFITANDLOSSPLANACTQ2903 with ZZ1_43EQ5BVBC64CKBXEY2QDEDAUOE
  
{ 
  ZZ1_TRANSACTIONKEY_APC as ZZ1_TRANSACTIONKEY_APC
}
