@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_E21173E3287F'

extend view C_GENERICPLANQ3001 with ZZ1_TMGM6YBKW4C76G3ZALEHZYVH7I
  
{ 
  ZZ1_PRICINGELEMENT_APC as ZZ1_PRICINGELEMENT_APC
}
