@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_73E58BDE0C5C'

extend view C_COSTCENTERQ2001 with ZZ1_CDRQWGNOVN5I3PNUUL3RTCZ5OM
  
{ 
  ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
