@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_DDA643349234'

extend view C_ALLOCATIONRUNRESULT with ZZ1_F523UUUL3DEIDMP3DHWDUUSITU
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
