@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_AED3A0B0F592'

extend view C_ALLOCRUNJOURNALENTRYITEM with ZZ1_4HBZU32CLHODJPCXW7FZGJEGRA
  
{ 
  _Extension.ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
