@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_38FE15946872'

extend view C_JRNLENTRYITEMCORRESPNC with ZZ1_DECMCRUKI7KLWNTW4I27KQPCUQ
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
