@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_D960004228A4'

extend view A_SUPPLIERINVOICEITEMGLACCT with ZZ1_ZRMJEFVOKBVFU5ZIQ32H6YXFPQ
  
{ 
  _ItemGLAcctExtension.ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
