@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_A0AB2FD9F29F'

extend view FINAC_SELECTION with ZZ1_EVAMGPPQBM6XWJFVAKKLREGIKE
  
{ 
  I_GLACCOUNTLINEITEM.ZZ1_SOURCE_COB as ZZ1_SOURCE_COB
}
