@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_7A38C34CB39B'

extend view C_GENERICPLANQ3001 with ZZ1_R4DZ5BBP5OPGRDZHTRYGWV6S54
  
{ 
  ZZ1_TRANSACTIONKEY_APC as ZZ1_TRANSACTIONKEY_APC
}
