@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_8D404D377BD1'

extend view C_MARKETSEGMENTQ2501 with ZZ1_LGLXQAVPDOHTF76V2TFFXZOK4A
  
{ 
  ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
