@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_8AFDC400117B'

extend view FINAC_SELECTION with ZZ1_R6JRDOUU4HIIGTIFQWNNL3MYX4
  
{ 
  I_GLACCOUNTLINEITEM.ZZ1_VEHICLENO_COB as ZZ1_VEHICLENO_COB
}
