@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_A05D6D26A010'

extend view C_SALESORDERQ2301 with ZZ1_Q4Q3U5YAAA4METBDUAIB7PU3OI
  
{ 
  ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
