@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_8069340DE175'

extend view C_AVGDAILYTRIALBALANCE with ZZ1_EQSUAQGUPPJ2K3ENGUHHP2IYYA
  
{ 
  I_AvgDailyBalKeyFig.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
