@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_4FB4B899654F'

extend view I_CNSLDTNPLANRPTDFINDATA with ZZ1_4KPIDEDOFSYBAGAGBNRR2ORBB4
  
{ 
  _Extension.ZZ1_CLIENTCODE_COB as ZZ1_CLIENTCODE_COB
}
