@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_351CD4C5E11E'

extend view C_FINPLANNINGDELETEITEM with ZZ1_YKN2RTLGGX5IBKCLQ4VQ2B6UIM
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
