@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_2E0680B3B395'

extend view I_GLACCOUNTLINEITEMRAWDATA with ZZ1_O2C65MVXEMSVKTPFAS3H3VRD4Q
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
