@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_4F8A9067EE7B'

extend view C_FUNCTIONALAREASQ2801 with ZZ1_MLCL34ZKJA4VLSPEYQZRIG7EOA
  
{ 
  ZZ1_PRODUCTCODE_COB as ZZ1_PRODUCTCODE_COB
}
