@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_B7547A43B466'

extend view C_PROFITCENTERPLANACTQ2701 with ZZ1_4HG34WO6C2ALPQ2SNJYNMLQHJA
  
{ 
  ZZ1_CLIENTCODE_APC as ZZ1_CLIENTCODE_APC
}
