@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_8DDACF9FED57'

extend view I_DRCTACTIVITYALLOCATIONITEMTP with ZZ1_ABWG2MRB2TY4GVWSZSBXY5PUP4
  
{ 
  _Extension.ZZ1_PRODUCTCODE_COB as ZZ1_PRODUCTCODE_COB
}
