@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_EA9F53005785'

extend view I_CNSLDTNPLANRPTDFINDATA with ZZ1_XZCEMPLV5MDPCGAYEJXFEKQNEU
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
