@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_81BCCAAE05C3'

extend view C_MARKETSEGMENTPLANACTQ2501 with ZZ1_E7LXTZAQFXG5KJW4CXXGXPUVSY
  
{ 
  ZZ1_VEHICLENO_APC as ZZ1_VEHICLENO_APC
}
