@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_3F144498CCC2'

extend view C_MATLDOCFORPRINTGDSISSSUBCONT with ZZ1_BK6PJ3D7BLFHA5SJWPEP7WGGHU
  
{ 
  _PrintExtension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
