@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_165B2E04D79B'

extend view I_GLACCTLINEITMSUBLDGRITMTYPEC with ZZ1_RU6SNWWI7N2DAZWXD5QO6VTOBE
  
{ 
  _Extension.ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
