@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_69F13F0B16EC'

extend view FAC_DART_Z3_GL_LEDGER_ITEM with ZZ1_PG3H6WT2IE5WFDCNNSWSWJOMDQ
  
{ 
  ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
