@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_F8173619AEAE'

extend view FINAC_SELECTION with ZZ1_XV2LN3NTWC4HJ3RJDUPP2F3O3U
  
{ 
  I_GLACCOUNTLINEITEM.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
