@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_8476A076B4E7'

extend view I_GLACCOUNTYEARTODATEBALANCEC with ZZ1_25GW6TWSWIMQB7AXMZKUUOZTF4
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
