@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_ECE8BE84F525'

extend view FIN_SUBVAL_JOURNALENTRYITEM with ZZ1_VYYQUFJDNYILOPS32ZFVE3UKZI
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
