@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_C31A68A43F2F'

extend view I_FINPLANNINGENTRYITEMCUBE with ZZ1_JV3STMLL3EQML7DJKT3K5KF5PQ
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
