@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_1E3E93B28CEC'

extend view I_MATRIXCNSLDTNFNDNFORYTDMODE with ZZ1_X7R3ZA37FWTHRFDC6PAQPJN3KM
  
{ 
  _Extension.ZZ1_PRODUCTCODE_CJE as ZZ1_PRODUCTCODE_CJE
}
