@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_1855B4DFC485'

extend view C_GLLINEITEMSQ0001 with ZZ1_CNQ5O5FEJOA32SROMDHIVCJJQU
  
{ 
  ZZ1_PRODUCTCODE_COB as ZZ1_PRODUCTCODE_COB
}
