@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_81D14DD7E5D6'

extend view FIN_SUBVAL_PLANNINGENTRYITEM with ZZ1_HQ6FFHNLQVFB6FHTJZJ7P4QLXE
  
{ 
  _Extension.ZZ1_CLIENTCODE_COB as ZZ1_CLIENTCODE_COB
}
