@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_677AC2907561'

extend view C_PROFITCENTERPLANACTQ2701 with ZZ1_WNVJDJSVAY5ADQMAEBT64EMSWY
  
{ 
  ZZ1_SERIALNO_APC as ZZ1_SERIALNO_APC
}
