@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_4B78E442B8AE'

extend view C_FINPLANNINGDELETEITEM with ZZ1_3W7WZE2BYQYTTRFR7FVKP7SMMA
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
