@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_AF63B06C22C7'

extend view E_OPERATIONALACCTGDOCITEM with ZZ1_72ZXCHF7R4FVHXD2TVEFVAY5BI
  
{ 
  Persistence.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
