@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_85435A91F7B3'

extend view I_ACCOUNTINGDOCUMENTJOURNAL with ZZ1_57SCBMFQE66HGJFNI6KNNVC6RQ
  
{ 
  _Extension.ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
