@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_9FDD0D73A8EB'

extend view I_DRCTACTIVITYALLOCATIONITEMTP with ZZ1_Q2MNITVYZKLPRXVJCAQY7PIHSQ
  
{ 
  _Extension.ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
