@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_F8C7FE636338'

extend view C_GLACCOUNTLINEITEMIMPACT with ZZ1_ELPHWWGU4T4CZT7LW7OCENKK2A
  
{ 
  _Extension.ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
