@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_2B65A6079E2E'

extend view FIN_SUBVAL_PLANNINGENTRYITEM with ZZ1_IH4CQRRENVFKF6ANXJBSAP3WJQ
  
{ 
  _Extension.ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
