@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_0D25BA60B413'

extend view I_MARGANLYSPRODANDSRVCCUBE with ZZ1_5VP42E6RE3D2GRBFMU2SPWJTKY
  
{ 
  _Extension.ZZ1_VEHICLENO_COB as ZZ1_VEHICLENO_COB
}
