@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_A1900E8D52C0'

extend view I_PROFITABILITYCUBE with ZZ1_WLHC23DTQD62IMBPEFAO56QTZY
  
{ 
  _Extension.ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
