@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_571ED77A7841'

extend view I_MATRIXCNSLDTNFOUNDATION_2 with ZZ1_PIFSALK6UPXRDXPPE3RMEBBKXA
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_CJE as ZZ1_PRICINGELEMENT_CJE
}
