@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_3480D06A00B0'

extend view I_REALTIMERPTDFINDATAENHCD with ZZ1_NYBOKBBLWZNHTCPKFMDAB654QQ
  
{ 
  _Extension.ZZ1_PRODUCTCODE_COB as ZZ1_PRODUCTCODE_COB
}
