@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_16CE7F43FED1'

extend view C_TRIALBALANCEQ0002 with ZZ1_RXBYXTSEELUBGDFHXLZXGHXYFI
  
{ 
  ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
