@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_96177BCC92E1'

extend view I_MATRIXCNSLDTNFOUNDATION_2 with ZZ1_NBZOH5IOBLH7MFXJTTVTDE4O2A
  
{ 
  _Extension.ZZ1_THIRDPARTYREF_CJE as ZZ1_THIRDPARTYREF_CJE
}
