@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_6E6A13362A9D'

extend view A_JOURNALENTRYITEMBASIC with ZZ1_CZZVGOYX5WVSFZAMHVYNGO5EAE
  
{ 
  ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
