@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_A42E71BC8171'

extend view I_COSTREVNREASSIGNMENTITEMTP with ZZ1_B5A3CI6NSZ4G5O5XJTT5GAL3FA
  
{ 
  _Extension.ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
