@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_E83B474E99D5'

extend view E_FINANCIALPLANNINGENTRYITEM with ZZ1_FBUVPX66O37FOYG6I6RT4BLQJ4
  
{ 
  Persistence.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
