@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_1EE904E2218F'

extend view A_JOURNALENTRYITEMBASIC with ZZ1_M6KAMEUJSCAAFEI5VAP7S74T5U
  
{ 
  ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
