@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_C0D80FBC09F0'

extend view C_MARKETSEGMENTPLANACTQ2501 with ZZ1_ONUIXAJU4O3SX7BGHUJQJG3YDM
  
{ 
  ZZ1_SERIALNO_APC as ZZ1_SERIALNO_APC
}
