@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_9A0AD614497C'

extend view FIN_SUBVAL_PLANNINGENTRYITEM with ZZ1_GHBDXVQN2DRO55CGISWESJQZQQ
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
