@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_374876BC178E'

extend view FAC_GLACCOUNTLINEITEM with ZZ1_HGRTP7FIOKNGKO35X76JJDT2HU
  
{ 
  I_GLACCOUNTLINEITEM.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
