@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_D103E0CFCC36'

extend view FAC_GLACCOUNTLINEITEM with ZZ1_TCGDMAGJD3EHWVW6AUUID5EACE
  
{ 
  I_GLACCOUNTLINEITEM.ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
