@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_D2561FE6CF8B'

extend view FAC_DART_Z3_GL_LEDGER_ITEM with ZZ1_ERXFDPUDZHVYEF4VJRBB3OSZZU
  
{ 
  ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
