@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_3857DD8A1663'

extend view C_MARKETSEGMENTPLANACTQ2501 with ZZ1_UBITU6T2PKJKHA6VNQMQVJLEEU
  
{ 
  ZZ1_CLIENTCODE_APC as ZZ1_CLIENTCODE_APC
}
