@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_EF073AE61D16'

extend view C_FUNCTIONALAREAPLANACTQ2801 with ZZ1_NIZMCRDZPLJPOY2RMRWFPQUY6M
  
{ 
  ZZ1_CLIENTCODE_APC as ZZ1_CLIENTCODE_APC
}
