@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_A64A1C1A23CA'

extend view E_SUPPLIERINVOICEITEMGLACCT with ZZ1_NPOHZ3R7M6WDY6AZDSWWDKQY5U
  
{ 
  Persistence.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
