@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_C5ABC9BE338A'

extend view C_FINANCIALSTATEMENTKPI with ZZ1_UODC2NGXS5FQG2BI4QOS2LUMUI
  
{ 
  ZZ1_PRICINGELEMENT_ASC as ZZ1_PRICINGELEMENT_ASC
}
