@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_AC52D3D557CE'

extend view I_COMPACTJOURNAL with ZZ1_5YLZHLZNH4PSM35JPLYV2YZP2M
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
