@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_84B9ACB5B743'

extend view I_MATRIXCNSLDTNFNDNPERIODIC with ZZ1_3CWQNFIU4BKX6BWMUORQS25M5Q
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_CJE as ZZ1_PRICINGELEMENT_CJE
}
