@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_3F56BBF652F2'

extend view C_SERVICEORDERQRY2401 with ZZ1_W34RGTRHBG4LOZFCOX5TCGGMDI
  
{ 
  ZZ1_PRODUCTCODE_COB as ZZ1_PRODUCTCODE_COB
}
