@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_A0D28C40AE2A'

extend view FAC_GLACCOUNTLINEITEM with ZZ1_JJHAAT4RPHIJPOQIH5JTUCZWA4
  
{ 
  I_GLACCOUNTLINEITEM.ZZ1_CLIENTCODE_COB as ZZ1_CLIENTCODE_COB
}
