@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_6BA402B0A1E0'

extend view I_MATRIXCNSLDTNFOUNDATION with ZZ1_G2GMNHTQHLTHJ7QX2HNLWXB2HE
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_CJE as ZZ1_PRICINGELEMENT_CJE
}
