@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_431F30DD0CC8'

extend view C_DRCTACTYALLOCATIONACTIVEITEM with ZZ1_JW65VYCTYJ7SODB5L4FHDBPGAA
  
{ 
  _Extension.ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
