@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_2D51A7E03BE6'

extend view I_GLACCTBALANCECOMPRNCUBE with ZZ1_HAXHZ265RIZRXUJV4ZWCMZAKHY
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
