@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_635E25814F77'

extend view A_FINPLANITEMSTAGINGAREA with ZZ1_WI3V3ZLUL2TLK3XMHMUXPXAWRA
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
