@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_77C5002514B3'

extend view I_JOURNALENTRYITEM with ZZ1_A6TRV33YYTVENYVJNR3ZUJHYMM
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
