@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_FC260DA78BD0'

extend view C_GLLINEITEMSQ0001 with ZZ1_OXR3B6IZCKQK2MM2SLBCS2EMYQ
  
{ 
  ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
