@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_04AAAF785868'

extend view E_CNSLDTNGROUPJRNLENTRYITEM with ZZ1_UIQCN7JIYP27TM2YOCVVG4Z23U
  
{ 
  Persistence.ZZ1_PRICINGELEMENT_CJE as ZZ1_PRICINGELEMENT_CJE
}
