@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_59098DFD9111'

extend view C_OPLACCTGDOCITEMCORRESPNC with ZZ1_PYB4YHT3SHPJRJ4Z5KAPTEXGPI
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
