@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_5D06888301E9'

extend view C_COSTCENTERPLANACTQ2001 with ZZ1_BWNITDZAWE4AKA4ZEFMGRGICSU
  
{ 
  ZZ1_ICNNO_APC as ZZ1_ICNNO_APC
}
