@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_0E8ECA6DBA9B'

extend view I_MATRIXCNSLDTNFOUNDATION with ZZ1_4TMRHHCFLYBVXRRI77C6SDA73E
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_CJE as ZZ1_TRANSACTIONKEY_CJE
}
