@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_3E6A66FDE218'

extend view C_ALLOCATIONRUNRESULT with ZZ1_L6LBN2TUIOYIZWMZSZN5C4FJRY
  
{ 
  _Extension.ZZ1_PRODUCTCODE_COB as ZZ1_PRODUCTCODE_COB
}
