@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_8C3541AFE394'

extend view I_FINPLANNINGENTRYITEMCUBE with ZZ1_35T4BVSHUBHE73HOUQ2B2HLNS4
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
