@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_BB8D45C77107'

extend view A_FINPLANENTRYITEMVARIABLEFIX with ZZ1_BIPGFSGV625ZT4UHUTYQUCWVRA
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
