@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_8FE7EA0747E0'

extend view C_PROJECTPLANACTQ2203 with ZZ1_HSI4U7YOBAAWX64QJHULEHO35A
  
{ 
  ZZ1_PRICINGELEMENT_APC as ZZ1_PRICINGELEMENT_APC
}
