@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_749348AE9088'

extend view A_FINPLANITEMSTAGINGAREA with ZZ1_SKPU5W3SPNLBHZQZ4LZ3AH7ANQ
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
