@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_A6F5C0E141EC'

extend view A_OPENINGBALANCE with ZZ1_GI7S7LTI7Z443UWPFEJO2BZ5QA
  
{ 
  ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
