@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_9BC493D7BAED'

extend view I_AVGDAILYBALGROUPREPORTING with ZZ1_7MMDOZRR4RHBGHW4RMES5T52NU
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
