@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_8F7FB4A72753'

extend view I_AVGDAILYBALGROUPREPORTING with ZZ1_EFTAUFMOYB3LNA22VGJ5RLZ55A
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
