@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_7A73EBA9CD86'

extend view I_CNSLDTNINTEGRPTDFINDATA with ZZ1_CJOD6LKQIZQPFQIHTXAARXIVQM
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
