@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_A40075A999B2'

extend view I_MATRIXCNSLDTNFNDNPERIODIC with ZZ1_4Y57M3UKGMDDBNZWCOAUICZU6E
  
{ 
  _Extension.ZZ1_THIRDPARTYREF_CJE as ZZ1_THIRDPARTYREF_CJE
}
