@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_A460BE84A7B7'

extend view C_REALTIMERPTDFINDATAENHCD with ZZ1_ET23ZL4AVVH7WUJFE4NM63STBY
  
{ 
  RealTimeRptdFinData.ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
