@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_BCD32AD7BC60'

extend view I_MATRIXCNSLDTNFNDNFORPERMODE with ZZ1_QWM76ASJPH4GM3556UM4CLF2NA
  
{ 
  _Extension.ZZ1_THIRDPARTYREF_CJE as ZZ1_THIRDPARTYREF_CJE
}
