@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_A38A9CBC4919'

extend view C_GLACCOUNTLINEITEMIMPACT with ZZ1_6WKW4VVL52EUY3PX4L356U47DU
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
