@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_629FF3894D26'

extend view A_FINPLANNINGENTRYITEMTP with ZZ1_UVT6XPDACIGDGNK2FU2MXSZNN4
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
