@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_E8842E9E8963'

extend view E_CNSLDTNGROUPJRNLENTRYITEM with ZZ1_XPF2OLIUA7HJSGQFTVSJ3VUTWY
  
{ 
  Persistence.ZZ1_THIRDPARTYREF_CJE as ZZ1_THIRDPARTYREF_CJE
}
