@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_83D85CEBC245'

extend view I_AVGDAILYBALGROUPREPORTING with ZZ1_N62AJQ4BYI3NQX4OIOD5VNAHUY
  
{ 
  _Extension.ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
