@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_3CDC38126C04'

extend view I_REALTIMERPTDFINDATAENHCD with ZZ1_52LNFD3UPZIHOMNXDB5IEPO3FI
  
{ 
  _Extension.ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
