@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_9FDDC02EEA93'

extend view C_ALLOCATIONRUNRESULTITEM with ZZ1_HB5CPWKCPVO2O2EVVDXPUAEPMI
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
