@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_44F1C348FBBC'

extend view I_MATRIXCNSLDTNFNDNFORPERMODE with ZZ1_TU4RFKOFRALUVH5CHY2M5ASOIM
  
{ 
  _Extension.ZZ1_PRODUCTCODE_CJE as ZZ1_PRODUCTCODE_CJE
}
