@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_33B064797979'

extend view C_GLACCOUNTFLOW with ZZ1_GG57KTDOINJFRH5NC45FAUYOTA
  
{ 
  ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
