@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_F7D9E5F604F0'

extend view C_INTERNALORDERPLANACTQ2101 with ZZ1_UZX6H35ANLPUD22PUSNI557NKY
  
{ 
  ZZ1_THIRDPARTYREF_APC as ZZ1_THIRDPARTYREF_APC
}
