@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_27800F83603C'

extend view I_DRCTACTIVITYALLOCATIONITEMTP with ZZ1_HTIFSWUEKAHZMG2X4RWBJRSNRY
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
