@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_D56C1A8780E5'

extend view I_MATRIXCNSLDTNFNDNFORPERMODE with ZZ1_IT5H3OB2CF3GQXL5XL2OP7R2II
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_CJE as ZZ1_TRANSACTIONKEY_CJE
}
