@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_523CD6BEB78D'

extend view E_FINPLANITEMSTAGINGAREA with ZZ1_PRIPSGHWDCUWSY73IGKYOBKMLU
  
{ 
  Persistence.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
