@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_2C35F82250DB'

extend view C_COSTCENTERPLANACTQ2001 with ZZ1_4GHDIVRRD6S7NXUKMHCGQTIS7Y
  
{ 
  ZZ1_PRICINGELEMENT_APC as ZZ1_PRICINGELEMENT_APC
}
