@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_ED965D80E6B7'

extend view C_PROJECTPLANACTQ2203 with ZZ1_RM7PLFJVND3K4F2O2PPZABV7LM
  
{ 
  ZZ1_PRODUCTCODE_APC as ZZ1_PRODUCTCODE_APC
}
