@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_31CC1B1AA971'

extend view A_FINPLANNINGENTRYITEM with ZZ1_IRLGHMJCZZE3WWKYRO7TYIJB6M
  
{ 
  ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
