@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_3893AAAF8102'

extend view I_ACCOUNTINGDOCUMENTJOURNAL with ZZ1_6VKQAASL7KEAB6T3ZL4ELRSQ2Y
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
