@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_2578D5FF4029'

extend view C_PROFITANDLOSSQ2901 with ZZ1_H6PXXHSJMEXI7KUJBFEDI2AE5A
  
{ 
  ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
