@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_FDA0D168A52F'

extend view I_GLACCOUNTYEARTODATEBALANCEC with ZZ1_56MSKIAKI4FEHKY6V5UBQ6S7KY
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
