@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_3440E96554BB'

extend view I_GLACCTLINEITMSUBLDGRITMTYPEC with ZZ1_FCH6GU4VVW2DHV4VYELKR7G5UM
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
