@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_35C9B776F897'

extend view C_COSTCENTERPLANACTQ2001 with ZZ1_OP2XUHDMFJ6ZFSJ3SS6TXLQEKE
  
{ 
  ZZ1_TRANSACTIONKEY_APC as ZZ1_TRANSACTIONKEY_APC
}
