@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_EBDB2C905EC0'

extend view C_PROFITANDLOSSPLANACTQ2903 with ZZ1_ZANUDKYWKYCLEW5KJCLCO4RWSE
  
{ 
  ZZ1_CLIENTCODE_APC as ZZ1_CLIENTCODE_APC
}
