@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_2BB9CD6CC7A2'

extend view C_PROFITANDLOSSPLANACTQ2903 with ZZ1_W3BN6M65JGUQNSD2DLVTI7O2EU
  
{ 
  ZZ1_PRICINGELEMENT_APC as ZZ1_PRICINGELEMENT_APC
}
