@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_0E94C4F5DDFC'

extend view I_MATRIXCNSLDTNFNDNPERIODIC with ZZ1_O2ZRPJFZFUBUTPXEMTIXW3TNWU
  
{ 
  _Extension.ZZ1_HOLMANPO_CJE as ZZ1_HOLMANPO_CJE
}
