@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_47523FD37957'

extend view I_REALTIMERPTDFINDATAENHCD with ZZ1_5QQCRNSSTCXTHTR3FPHQIQOZLY
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
