@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_B4BE7DEC7EEC'

extend view I_COSTREVNREASSIGNMENTITEMTP with ZZ1_7UKCSEPCHXYAEJN7TTI3TKDRII
  
{ 
  _Extension.ZZ1_SERIALNO_COB as ZZ1_SERIALNO_COB
}
