@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_4E06C48D7308'

extend view C_PROFITCENTERPLANACTQ2701 with ZZ1_H6D3LRJCT7ZGXZCGKGLYH2UVBY
  
{ 
  ZZ1_PRODUCTCODE_APC as ZZ1_PRODUCTCODE_APC
}
