@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_2BECADD825B5'

extend view C_PROFITCENTERPLANACTQ2701 with ZZ1_GJI6THFHNDW66KEOQLO7IUTMZI
  
{ 
  ZZ1_PRICINGELEMENT_APC as ZZ1_PRICINGELEMENT_APC
}
