@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_86160368B412'

extend view I_GLACCOUNTLINEITEMCUBE with ZZ1_3JWPIMW7PQNESKHDNNXEMM67XE
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
