@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_B0AAC60DFC3D'

extend view C_JOURNALENTRYITEMBROWSER with ZZ1_FQU2M3HNCQMEPPUJCEUYJRG65A
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
