@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_699A30F03598'

extend view C_SERVICEORDERQRY2401 with ZZ1_NODATVKRCGRA3H42MSE2AENGX4
  
{ 
  ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
