@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_452920D78D98'

extend view C_SALESORDERQ2301 with ZZ1_GPV5AVZZV2QOXYSSWQ3NMKIS2I
  
{ 
  ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
