@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_3DCA38106573'

extend view C_GENERICPLANQ3001 with ZZ1_VXWEYQQEQC52HGBOMHZSXBPMPQ
  
{ 
  ZZ1_SERIALNO_APC as ZZ1_SERIALNO_APC
}
