@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_49131E5C7AAF'

extend view A_OPENINGBALANCE with ZZ1_Z5HLU33TCVLCOMVABG5NA6UWSM
  
{ 
  ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
