@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_28D9A84127DF'

extend view A_FINPLANNINGENTRYITEM with ZZ1_KGSQVAVGVBREXDWIQF3RWNZMBM
  
{ 
  ZZ1_CLIENTCODE_COB as ZZ1_CLIENTCODE_COB
}
