@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_4091664F7387'

extend view FINAC_SELECTION with ZZ1_3IEPAXJRUT5OG23QIIRWA6X5MI
  
{ 
  I_GLACCOUNTLINEITEM.ZZ1_HOLMANPO_COB as ZZ1_HOLMANPO_COB
}
