@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_F39A7D3FA60C'

extend view C_FINANCIALSTATEMENTKPI with ZZ1_E3STNNQWQFIZ4RI2WCGYJYIOSM
  
{ 
  ZZ1_SERIALNO_ASC as ZZ1_SERIALNO_ASC
}
