@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_AD21E992BE37'

extend view P_GLACCOUNTBALANCE with ZZ1_F7GSXRHWAZW3UC2MJAY66VWJDI
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
