@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_622F70141215'

extend view A_FINPLANENTRYITEMVARIABLEFIX with ZZ1_242KDOBJ572E5YWNHP5ECVJTME
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
