@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_46D837270D8C'

extend view C_JOURNALENTRYITEMBROWSER with ZZ1_YBSCGBKAYKHGRECKJVHARVEENA
  
{ 
  _Extension.ZZ1_PRODUCTCODE_COB as ZZ1_PRODUCTCODE_COB
}
