@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_15A49E25ECC6'

extend view C_FUNCTIONALAREAPLANACTQ2801 with ZZ1_XIVD7FMHPCPGZ7XDNO7DDYS7KM
  
{ 
  ZZ1_VEHICLENO_APC as ZZ1_VEHICLENO_APC
}
