@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_F056EC0A0158'

extend view C_SALESORDERQ2301 with ZZ1_PVCRLFSWDD5ZBEQBK5AHNA3LTU
  
{ 
  ZZ1_PRODUCTCODE_COB as ZZ1_PRODUCTCODE_COB
}
