@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_B5D3DBAD6F51'

extend view C_INTERNALORDERPLANACTQ2101 with ZZ1_WEWLXRE4FDGATJHA6N44R5WERE
  
{ 
  ZZ1_PRODUCTCODE_APC as ZZ1_PRODUCTCODE_APC
}
