@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_752412A04A4E'

extend view C_GLACCOUNTFLOW with ZZ1_KXM2DGUECDYJ27JOZZPNAYGOCQ
  
{ 
  ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
