@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_A67532766470'

extend view A_GLACCOUNTLINEITEM with ZZ1_CDYHG6NSPOKAYDRE2YFSFCKPFM
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
