@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_282E4BDF7A47'

extend view FINAC_SELECTION with ZZ1_TCJQ2A2GELWN6SV3HRSVYYQMM4
  
{ 
  I_GLACCOUNTLINEITEM.ZZ1_CLIENTCODE_COB as ZZ1_CLIENTCODE_COB
}
