@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_C7212FF807C3'

extend view I_AVGDAILYBALKEYFIGCUBE with ZZ1_D47OMLQYSEFNHUGVD5JNFTAZAM
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
