@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_5265C9396991'

extend view FINAC_SELECTION with ZZ1_BKAGKVYE5FP55HZYNV4AOOZTKY
  
{ 
  I_GLACCOUNTLINEITEM.ZZ1_SERIALNO_COB as ZZ1_SERIALNO_COB
}
