@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_BA2527B62EFC'

extend view FAC_GLACCOUNTLINEITEM with ZZ1_OVOA3YXQYEJW74NF3Y65YFW36E
  
{ 
  I_GLACCOUNTLINEITEM.ZZ1_SERIALNO_COB as ZZ1_SERIALNO_COB
}
