@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_7D74B86F8D89'

extend view C_GLACCOUNTLINEITEMIMPACT with ZZ1_WBOLQIMATEGC4XVWBUIMCBS67A
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
