@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_2E2D7A66A72A'

extend view C_TRIALBALANCEQ0001 with ZZ1_VHUKPQHDHAZGKXDNIQJLLIEBZM
  
{ 
  ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
