@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_672460BBF5BC'

extend view C_FUNCTIONALAREASQ2801 with ZZ1_HZRNSA2M5DIBPWN3XFKISULAAM
  
{ 
  ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
