@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_ED6BF143E24D'

extend view ESH_S_INC_INVOICE with ZZ1_DSIQHPFVJ5NJTC4HK4BKWY3ZPA
  
{ 
  _HEADEREXTENSION.ZZ1_INVOICENO_MIH as ZZ1_INVOICENO_MIH
}
