@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_097608379F81'

extend view I_JOURNALENTRYITEM with ZZ1_M63OI7B76362QTEAUB3ZG2FAZM
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
