@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_C6F8197D3C11'

extend view A_JOURNALENTRYITEMBASIC with ZZ1_WJHUKQV4EXQUNWLCQA2JL4MFLU
  
{ 
  ZZ1_CLIENTCODE_COB as ZZ1_CLIENTCODE_COB
}
