@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_3188C3A360B1'

extend view E_FINANCIALPLANNINGENTRYITEM with ZZ1_ACDIDHDAMEZB6I32ADIAGELBIU
  
{ 
  Persistence.ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
