@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_E0DFF2DB73FA'

extend view C_FUNCTIONALAREASQ2801 with ZZ1_KKCNPN4NYM46HC6Z7Y4YXOFOWU
  
{ 
  ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
