@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_4834D43EF70A'

extend view A_FINPLANNINGENTRYITEM with ZZ1_YRS24KCIO3OHQLFXX56FAKKWUE
  
{ 
  ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
