@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_BC68E820E914'

extend view C_PROFITANDLOSSQ2901 with ZZ1_6DAPUGSDP2FWMQJCVJVMPTSTDA
  
{ 
  ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
