@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_1E189AE779DE'

extend view C_PROFITANDLOSSPLANACTQ2903 with ZZ1_SNXZCNOLEX7536I3WL5XFKXSZE
  
{ 
  ZZ1_HOLMANPO_APC as ZZ1_HOLMANPO_APC
}
