@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_F091B554BE0A'

extend view C_PROFITCENTERPLANACTQ2701 with ZZ1_MF2IF5OBUQQ5WWUQP6XLAPTNGE
  
{ 
  ZZ1_VEHICLENO_APC as ZZ1_VEHICLENO_APC
}
