@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_C037F27D736C'

extend view C_DRCTACTYALLOCATIONACTIVEITEM with ZZ1_ZE2FZYEACLGVOLNT6N7MIVEDFY
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
