@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_1EE725948244'

extend view C_COSTREVNREASSGMTACTIVEITEM with ZZ1_KEUC5PKO4UXLGK77ZSQWC7BA2Y
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
