@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_9EDD8426E04F'

extend view I_AVGDAILYBALKEYFIGCUBE with ZZ1_VY5WAQ4HI5NCXYEIM4EGVTIE5U
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
