@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_C2407D942A5A'

extend view C_COSTCENTERPLANACTQ2001 with ZZ1_3KPZVJ7KDSZK5HNKYBDKU4L2TE
  
{ 
  ZZ1_THIRDPARTYREF_APC as ZZ1_THIRDPARTYREF_APC
}
