@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_C233D9AC3670'

extend view C_ALLOCATIONRUNRESULTITEM with ZZ1_UWBWW3BKGK4A7RFCDRBN7P3WMI
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
