@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_1F520FCF0FC4'

extend view FAC_GLACCOUNTLINEITEM with ZZ1_ELBGJQLQ3VANGJ36P4MX2Q2MOA
  
{ 
  I_GLACCOUNTLINEITEM.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
