@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_B841AF4176F7'

extend view I_GLACCOUNTYEARTODATEBALANCEC with ZZ1_KGUADZTUVY6H44VSAJM5LF64CU
  
{ 
  _Extension.ZZ1_PRODUCTCODE_COB as ZZ1_PRODUCTCODE_COB
}
