@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_DE5866A313FD'

extend view C_FUNCTIONALAREAPLANACTQ2801 with ZZ1_5UON3KGS26UNMSWJYEVJXEXRYI
  
{ 
  ZZ1_TRANSACTIONKEY_APC as ZZ1_TRANSACTIONKEY_APC
}
