@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_BBBCE59578E0'

extend view I_GLACCOUNTLINEITEM with ZZ1_WOSI3S3762VCTIGKA4LKEMOISQ
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
