@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_D8D07A1C09E9'

extend view C_SERVICEORDERQRY2401 with ZZ1_VRODJGNFJT5GA2OVVSSY53BHKA
  
{ 
  ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
