@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_242AD2212881'

extend view E_ARPOSTGRULEACTNGL with ZZ1_NXI2KDI746QPYL3MG5TOSB2YIA
  
{ 
  Persistence.ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
