@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_3FB078426AAD'

extend view C_INTERNALORDERPLANACTQ2101 with ZZ1_6OIHE6QQOQ5ZG4YLPLM7PM3ZGM
  
{ 
  ZZ1_CLIENTCODE_APC as ZZ1_CLIENTCODE_APC
}
