@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_4357C298A5C5'

extend view C_JOURNALENTRYITEMBROWSER with ZZ1_E6RHKN5PTLJ2PCLDBJP3OUR6ZQ
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
