@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_552662432BB2'

extend view FINAC_SELECTION with ZZ1_D6HXZC2S7UKOUAFNPFHV4QY6MU
  
{ 
  I_GLACCOUNTLINEITEM.ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
