@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_7495FB1F441E'

extend view FAC_GLACCOUNTLINEITEM with ZZ1_K72RFNRTT4BD3HOQO6ASCXLUPE
  
{ 
  I_GLACCOUNTLINEITEM.ZZ1_HOLMANPO_COB as ZZ1_HOLMANPO_COB
}
