@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_9F3A826A3347'

extend view I_GLACCOUNTLINEITEMRAWDATA with ZZ1_77PRHLDMLGKRC3VIL4PPL5H7NY
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
