@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_34ACD690744E'

extend view FAC_GLACCOUNTLINEITEM with ZZ1_XSRAQQE72P4IIOHM5OOXBCXGHQ
  
{ 
  I_GLACCOUNTLINEITEM.ZZ1_PRODUCTCODE_COB as ZZ1_PRODUCTCODE_COB
}
