@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_B7197961C50E'

extend view C_ALLOCATIONRUNRESULTITEM with ZZ1_WWIXVXF7LSRUUYD6PJJKDQTDYM
  
{ 
  _Extension.ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
