@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_907EC3ED0C54'

extend view I_MARGANLYSPRODANDSRVCCUBE with ZZ1_55PGT5CJQNORAL2HIXLSEMEFLY
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
