@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_F64126837366'

extend view I_MARGANLYSPRODANDSRVCCUBE with ZZ1_26GWONZTBGWSLC7WIBXYZ2OKII
  
{ 
  _Extension.ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
