@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_DDE8719BB30E'

extend view I_GLACCTLINEITMSUBLDGRITMTYPEC with ZZ1_YPM2UCZFLO2AJO2NSZK2UNLA3U
  
{ 
  _Extension.ZZ1_SERIALNO_COB as ZZ1_SERIALNO_COB
}
