@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_4DCC61C8AE24'

extend view C_INTERNALORDERPLANACTQ2101 with ZZ1_NUPNGU526KGDDKYGCTLKZYYZTU
  
{ 
  ZZ1_VEHICLENO_APC as ZZ1_VEHICLENO_APC
}
