@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_9D77EB2EF1CA'

extend view C_FUNCTIONALAREAPLANACTQ2801 with ZZ1_S3P5UG72FP6YDMJLBPQ7MKMADY
  
{ 
  ZZ1_HOLMANPO_APC as ZZ1_HOLMANPO_APC
}
