@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_AC4F25B833D2'

extend view C_MARKETSEGMENTPLANACTQ2501 with ZZ1_CRQNNYVVXZM563SLQZWOD4E5CE
  
{ 
  ZZ1_PRODUCTCODE_APC as ZZ1_PRODUCTCODE_APC
}
