@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_E0A330FCD9C4'

extend view I_GLACCOUNTLINEITEMSEMTAG with ZZ1_FFCFBUZQQJJC7EGH5FDJXSHQ5A
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
