@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_64844E137435'

extend view I_MARGANLYSPRODANDSRVCCUBE with ZZ1_I4WKKQRA4NJ5GZYRKTLHA64MIA
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
