@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_DECF5CC43595'

extend view I_ACCOUNTINGDOCUMENTJOURNAL with ZZ1_PHPKVC2MVA6QGB6CPE6ZUEXRRU
  
{ 
  _Extension.ZZ1_VEHICLENO_COB as ZZ1_VEHICLENO_COB
}
