@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_047F648DBEF8'

extend view C_MARKETSEGMENTQ2501 with ZZ1_L523J47JHCKHZQBEK7AM65QQLI
  
{ 
  ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
