@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_C59130D8E02B'

extend view C_COSTCENTERPLANACTQ2001 with ZZ1_XMD6JVNGERG5F52DIYHTGRBDJY
  
{ 
  ZZ1_VEHICLENO_APC as ZZ1_VEHICLENO_APC
}
