@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_F4D9E653D4E9'

extend view C_MARKETSEGMENTPLANACTQ2501 with ZZ1_OGUCKLJEAL5BSIE36DVX62HD4U
  
{ 
  ZZ1_TRANSACTIONKEY_APC as ZZ1_TRANSACTIONKEY_APC
}
