@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_83788E82BF7A'

extend view E_FINPLANITEMSTAGINGAREA with ZZ1_7YBG3MBVWOBMAVD2RLE77OVXJA
  
{ 
  Persistence.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
