@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_6E2C88C72046'

extend view C_TRIALBALANCEQ0001 with ZZ1_FKXILAL7ABOOEHK6L5DBQYAQDA
  
{ 
  ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
