@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_322AC5BA9AD9'

extend view I_CNSLDTNINTEGRPTDFINDATA with ZZ1_SDAXXDDXYJLIWGRS5UN7IYFEAQ
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
