@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_1489C19ABE5E'

extend view C_JRNLENTRYITEMCORRESPNC with ZZ1_OZRNZQOFBK3LV7TWPNKNIUPDFU
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
