@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_8BBDDE780F8E'

extend view C_COSTCENTERQ2001 with ZZ1_DDUILTZLUASFLCHQEQXLOAGTI4
  
{ 
  ZZ1_PRODUCTCODE_COB as ZZ1_PRODUCTCODE_COB
}
