@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_832720C24DA7'

extend view C_PROFITCENTERPLANACTQ2701 with ZZ1_FPRUTFGBNLE7QZXFRTGWCPAPWM
  
{ 
  ZZ1_THIRDPARTYREF_APC as ZZ1_THIRDPARTYREF_APC
}
