@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_689E41124580'

extend view I_GLACCOUNTYEARTODATEBALANCEC with ZZ1_HFHO5HAOO2DSLDGGJP3NN5JDJA
  
{ 
  _Extension.ZZ1_VEHICLENO_COB as ZZ1_VEHICLENO_COB
}
