@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_AFFBD3B77354'

extend view FAC_GLACCOUNTLINEITEM with ZZ1_HA7LBVEDR5XLLLCF6DN7S4GPEY
  
{ 
  I_GLACCOUNTLINEITEM.ZZ1_VEHICLENO_COB as ZZ1_VEHICLENO_COB
}
