@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_D00A1240F3C1'

extend view C_FINANCIALSTATEMENTKPI with ZZ1_47J263VZJMS7I2OLJKFBELOU4U
  
{ 
  ZZ1_THIRDPARTYREF_ASC as ZZ1_THIRDPARTYREF_ASC
}
