@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_81343D79A496'

extend view C_PROFITANDLOSSPLANACTQ2903 with ZZ1_ZOYOJZIDSVCQ2E37U4BQ7COK4M
  
{ 
  ZZ1_SERIALNO_APC as ZZ1_SERIALNO_APC
}
