@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_28F7765DEDE8'

extend view C_GLLINEITEMSQ0001 with ZZ1_WPDGLFEZEQOZVPVYOTGINK5NOE
  
{ 
  ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
