@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_EF0A43AAB397'

extend view I_GLACCOUNTLINEITEMRAWDATA with ZZ1_YFZSJLPU3GH6PKGUI5HKDHWP2M
  
{ 
  _Extension.ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
