@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_168352903A73'

extend view C_INTERNALORDERPLANACTQ2101 with ZZ1_3U7ZLMDUEQGCGZF5JZL4PH5DTU
  
{ 
  ZZ1_SERIALNO_APC as ZZ1_SERIALNO_APC
}
