@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_3B3E4BEB9AFA'

extend view C_FUNCTIONALAREAPLANACTQ2801 with ZZ1_4TTCM7AXB2FDYFHHRX2FLZDZOA
  
{ 
  ZZ1_PRODUCTCODE_APC as ZZ1_PRODUCTCODE_APC
}
