@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_1EAAE329DFF2'

extend view C_TRIALBALANCEQ0001 with ZZ1_F4NXNOSPLLM7V2VKSCUOQS37HE
  
{ 
  ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
