@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_819C6AF309E5'

extend view C_PROFITCENTERPLANACTQ2701 with ZZ1_O6KS33GBPB42U7FVZCOY7IZ3VI
  
{ 
  ZZ1_TRANSACTIONKEY_APC as ZZ1_TRANSACTIONKEY_APC
}
