@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_C704BBCDB813'

extend view I_GLACCTLINEITMSUBLDGRITMTYPEC with ZZ1_7ARESTWPOXA4TLQAO5TP5324QM
  
{ 
  _Extension.ZZ1_PRODUCTCODE_COB as ZZ1_PRODUCTCODE_COB
}
