@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_D4C8641485FC'

extend view A_FINPLANENTRYITEMVARIABLEFIX with ZZ1_X7PP5O7DARCXE4LNM34C4ZHLYI
  
{ 
  _Extension.ZZ1_PRODUCTCODE_COB as ZZ1_PRODUCTCODE_COB
}
