@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_F7EBA6A40844'

extend view A_JOURNALENTRYITEMBASIC with ZZ1_HRM52JTSD5LVXVSRPJNZZ2NN2M
  
{ 
  ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
