@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_FCD4D93FCCAC'

extend view C_MARKETSEGMENTPLANACTQ2501 with ZZ1_LOQF7WHYRF3ZAR66GQS5BZGBHE
  
{ 
  ZZ1_HOLMANPO_APC as ZZ1_HOLMANPO_APC
}
