@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_87618E94FF63'

extend view I_GLACCOUNTYEARTODATEBALANCEC with ZZ1_G63RU4QHDJTWUVWG7B45PPGCEA
  
{ 
  _Extension.ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
