@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_AFD414C877D4'

extend view C_GOODSMOVEMENTQUERY with ZZ1_RAH2SM7GTJOSPNXMSFHHV7ALC4
  
{ 
  ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
