@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_CD5D003DD6AF'

extend view C_GOODSMOVEMENTQUERY with ZZ1_XK55QMJG4RUVJVLC6BFR5MQNNY
  
{ 
  ZZ1_PRODUCTCODE_COB as ZZ1_PRODUCTCODE_COB
}
