@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_13922649821C'

extend view I_DRCTACTIVITYALLOCATIONITEMTP with ZZ1_SAZAPVMXPICAEBNCCVTIPIREHY
  
{ 
  _Extension.ZZ1_CLIENTCODE_COB as ZZ1_CLIENTCODE_COB
}
