@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_B00E1C011B72'

extend view C_OPLACCTGDOCITEMCORRESPNC with ZZ1_ILGKBMO3SEQP2B7KYDR5EP53LI
  
{ 
  _Extension.ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
