@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_A48E65062E91'

extend view I_GLACCTLINEITMSUBLDGRITMTYPEC with ZZ1_YZRM7BSKJVI2SMQZMTODGRMYTE
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
