@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_67BFA6E21653'

extend view I_GLACCTBALANCECUBE with ZZ1_QTODHGWADPU2ED4S2ZEAVQM25I
  
{ 
  _Extension.ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
