@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_23D67F9109A2'

extend view E_SUPPLIERINVOICEITEMGLACCT with ZZ1_23ZV5ESBPEBQGJ4AJDN7MJQGQM
  
{ 
  Persistence.ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
