@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_A1BC98F947C5'

extend view C_FUNCTIONALAREAPLANACTQ2801 with ZZ1_5264JJNSHXMM5DIG6X4JPT6RLI
  
{ 
  ZZ1_PRICINGELEMENT_APC as ZZ1_PRICINGELEMENT_APC
}
