@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_4D83A26FFDB6'

extend view C_FUNCTIONALAREASQ2801 with ZZ1_THKIHGIEE33Q3KHX7GICGWUJAE
  
{ 
  ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
