@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_46E55EE69DE8'

extend view C_MATLDOCFORPRINTGDSISSSUBCONT with ZZ1_HB242VWWPI24CPTOJOJEWUNN3Y
  
{ 
  _PrintExtension.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
