@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_946B2DDE7BAA'

extend view E_SUPPLIERINVOICEITEMGLACCT with ZZ1_SZ2UMBUASRICIY4O7M7FEOQIKY
  
{ 
  Persistence.ZZ1_VEHICLENO_COB as ZZ1_VEHICLENO_COB
}
