@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_5E6579F3AADC'

extend view I_COSTREVNREASSIGNMENTITEMTP with ZZ1_EAUSBAQWMRRSFPOQXS4B23XEUE
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
