@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_9CD0A92B2DCB'

extend view I_MATRIXCNSLDTNFNDNFORYTDMODE with ZZ1_LMIIUWPSE3X73O6637WSQPMYVQ
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_CJE as ZZ1_PRICINGELEMENT_CJE
}
