@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_27EF580CBF7F'

extend view E_OPERATIONALACCTGDOCITEM with ZZ1_C7L22BZKHLRU3HPNSVC5G5LI4Y
  
{ 
  Persistence.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
