@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_9722F4754D0A'

extend view C_REALTIMERPTDFINDATAENHCD with ZZ1_SUOG3M76LU2JFC3QWNLTNLASWY
  
{ 
  RealTimeRptdFinData.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
