@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_AFA52BB35679'

extend view C_MARKETSEGMENTQ2501 with ZZ1_YH52CAPF4PU4WMMWWONIPFN3EQ
  
{ 
  ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
