@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_BA97539B32C2'

extend view C_PROJECTQ2201 with ZZ1_7NUJ6X4Y4NUMI3ZUVIQSSO5D6A
  
{ 
  ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
