@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_A111544C9B5E'

extend view C_MARKETSEGMENTPLANACTQ2501 with ZZ1_OWK2IT7RTTDTQYSQNLBBHPESKM
  
{ 
  ZZ1_THIRDPARTYREF_APC as ZZ1_THIRDPARTYREF_APC
}
