@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_8E864940A185'

extend view C_TRIALBALANCEQ0002 with ZZ1_PRQEW73QGXOAJNJB2GYC5YVXDY
  
{ 
  ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
