@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_EA92AD0A9951'

extend view C_PROFITANDLOSSQ2901 with ZZ1_DOWJ63N5EMGBPL23ERZP2KM5HQ
  
{ 
  ZZ1_VEHICLENO_COB as ZZ1_VEHICLENO_COB
}
