@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_902D56CE2EB6'

extend view I_MATRIXCNSLDTNFNDNFORPERMODE with ZZ1_QJZQSHU74XW2HV3WWFJ777MIUY
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_CJE as ZZ1_PRICINGELEMENT_CJE
}
