@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_36A2D4881DBA'

extend view A_FINPLANNINGENTRYITEM with ZZ1_2IV7V4FKAKIUTUYOW64HLQH5OY
  
{ 
  ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
