@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_809A92519635'

extend view C_FINANCIALSTATEMENTKPI with ZZ1_S3PK3ZB3JF4CEZDQVV6G4ZS3YU
  
{ 
  ZZ1_CLIENTCODE_ASC as ZZ1_CLIENTCODE_ASC
}
