@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_D84FF0B7DE0C'

extend view C_FUNCTIONALAREAPLANACTQ2801 with ZZ1_TWQKSD2NQGPDEFVGSOG5XXKPDY
  
{ 
  ZZ1_THIRDPARTYREF_APC as ZZ1_THIRDPARTYREF_APC
}
