@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_D9336A511AF8'

extend view C_PROJECTPLANACTQ2201 with ZZ1_QENK242PDTSBG73CKXSLYOVYIA
  
{ 
  ZZ1_THIRDPARTYREF_APC as ZZ1_THIRDPARTYREF_APC
}
