@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_1D013377B3F2'

extend view C_COSTCENTERQ2001 with ZZ1_SITSTRB6ND5XPBQVRWNHIUM4UY
  
{ 
  ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
