@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_0C6F1F139430'

extend view I_CNSLDTNPLANRPTDFINDATA with ZZ1_GBX62TBHCL5TYTCFWMRMOPF6DI
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
