@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_BDFA25589F2C'

extend view I_MATRIXCNSLDTNFOUNDATION_2 with ZZ1_N7P4SI4RXXBFRMDQB2IRA7K4BM
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_CJE as ZZ1_TRANSACTIONKEY_CJE
}
