@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_73FDBA162B72'

extend view C_FINANCIALSTATEMENTKPI with ZZ1_HDRQR5GKCJMLSCXD4FQBHJ5YAE
  
{ 
  ZZ1_PRODUCTCODE_ASC as ZZ1_PRODUCTCODE_ASC
}
