@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_1EC37B51D28E'

extend view I_JOURNALENTRYITEM with ZZ1_DQFDKGDUWAP7I7CSUY7B2PJSDM
  
{ 
  _Extension.ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
