@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_1A248A0C9362'

extend view C_DRCTACTYALLOCATIONACTIVEITEM with ZZ1_LJY6WCSCDXLXIPYT2F7ZOIK6CU
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
