@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_E79D06EE5DBC'

extend view C_PROFITABILITY_Q0002 with ZZ1_WWZSWKIOTQAXFAJ2KMQFGXFM7U
  
{ 
  ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
