@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_EC99EC82B82F'

extend view C_GOODSMOVEMENTQUERY with ZZ1_VR5UOPUSTD3XMTORFK33PFHGNU
  
{ 
  ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
