@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_467AF2DA52C0'

extend view C_MATLDOCFORPRINTGDSISSSUBCONT with ZZ1_3Z3XK6IXK4SLE46MIWL3ZP7UN4
  
{ 
  _PrintExtension.ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
