@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_BF9B662912B7'

extend view C_INTERNALORDERPLANACTQ2101 with ZZ1_ZKPRUYCKEOTH2NJMLCKNG6KJMU
  
{ 
  ZZ1_ICNNO_APC as ZZ1_ICNNO_APC
}
