@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_C3DD18298EE6'

extend view I_FINPLANNINGENTRYITEMCUBE with ZZ1_FQ7CREEBMMCF5ZWNB6C6XPOWOQ
  
{ 
  _Extension.ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
