@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_B373E59234C6'

extend view FIN_SUBVAL_PLANNINGENTRYITEM with ZZ1_A6CJGLHLOBBLBFBI363PMR7CSY
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
