@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_2014AEB529FB'

extend view C_INTERNALORDERPLANACTQ2101 with ZZ1_2RAMY7H2WV5Y4MAB2NHI7WSSZA
  
{ 
  ZZ1_PRICINGELEMENT_APC as ZZ1_PRICINGELEMENT_APC
}
