@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_9ADDDFBF641B'

extend view I_GLACCOUNTLINEITEMSEMTAG with ZZ1_ENGCO3XLA5CRSMBOR4OPZCGI74
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
