@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_7C4FE5474C72'

extend view C_COSTCENTERPLANACTQ2001 with ZZ1_4KTPQYEKLQX2UWENYYXLCQ2FVI
  
{ 
  ZZ1_CLIENTCODE_APC as ZZ1_CLIENTCODE_APC
}
