@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_5209A5438B09'

extend view FIN_SUBVAL_JOURNALENTRYITEM with ZZ1_QOYHGVBXATRKKPSPXQGTGHHILA
  
{ 
  _Extension.ZZ1_TRANSACTIONKEY_COB as ZZ1_TRANSACTIONKEY_COB
}
