@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_4A6990C7B8ED'

extend view C_ALLOCRUNJOURNALENTRYITEM with ZZ1_LL2TORQXXDWSGCKQV5K73P5O2E
  
{ 
  _Extension.ZZ1_PRICINGELEMENT_COB as ZZ1_PRICINGELEMENT_COB
}
