@AbapCatalog.internal.setChange: 'FLDADD_NO_ASS_INFLUENCE'
@AbapCatalog.sqlViewAppendName: 'ZZ1_3184A740E738'

extend view FIN_SUBVAL_JOURNALENTRYITEM with ZZ1_KAIYV3OMNDETPF76FNIKRIV2KM
  
{ 
  _Extension.ZZ1_THIRDPARTYREF_COB as ZZ1_THIRDPARTYREF_COB
}
